/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComoViverRouteImport } from './routes/como-viver'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ForcaDaOracaoRouteImport } from './routes/forca-da-oracao'
import { Route as IntroducaoRouteImport } from './routes/introducao'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as PalavraAoLeitorRouteImport } from './routes/palavra-ao-leitor'
import { Route as PorQue40DiasRouteImport } from './routes/por-que-40-dias'
import { Route as ApresentacaoIndexRouteImport } from './routes/apresentacao.index'
import { Route as ApresentacaoCaminhadaRouteImport } from './routes/apresentacao.caminhada'
import { Route as ApresentacaoFamiliaRouteImport } from './routes/apresentacao.familia'
import { Route as DiaNumeroRouteImport } from './routes/dia.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoViverRoute = ComoViverRouteImport.update({
  id: '/como-viver',
  path: '/como-viver',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcaDaOracaoRoute = ForcaDaOracaoRouteImport.update({
  id: '/forca-da-oracao',
  path: '/forca-da-oracao',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroducaoRoute = IntroducaoRouteImport.update({
  id: '/introducao',
  path: '/introducao',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const PalavraAoLeitorRoute = PalavraAoLeitorRouteImport.update({
  id: '/palavra-ao-leitor',
  path: '/palavra-ao-leitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQue40DiasRoute = PorQue40DiasRouteImport.update({
  id: '/por-que-40-dias',
  path: '/por-que-40-dias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoIndexRoute = ApresentacaoIndexRouteImport.update({
  id: '/apresentacao/',
  path: '/apresentacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoCaminhadaRoute = ApresentacaoCaminhadaRouteImport.update({
  id: '/apresentacao/caminhada',
  path: '/apresentacao/caminhada',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoFamiliaRoute = ApresentacaoFamiliaRouteImport.update({
  id: '/apresentacao/familia',
  path: '/apresentacao/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaNumeroRoute = DiaNumeroRouteImport.update({
  id: '/dia/$numero',
  path: '/dia/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-viver': typeof ComoViverRoute
  '/entrar': typeof EntrarRoute
  '/forca-da-oracao': typeof ForcaDaOracaoRoute
  '/introducao': typeof IntroducaoRoute
  '/jornada': typeof JornadaRoute
  '/palavra-ao-leitor': typeof PalavraAoLeitorRoute
  '/por-que-40-dias': typeof PorQue40DiasRoute
  '/apresentacao/caminhada': typeof ApresentacaoCaminhadaRoute
  '/apresentacao/familia': typeof ApresentacaoFamiliaRoute
  '/dia/$numero': typeof DiaNumeroRoute
  '/apresentacao/': typeof ApresentacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-viver': typeof ComoViverRoute
  '/entrar': typeof EntrarRoute
  '/forca-da-oracao': typeof ForcaDaOracaoRoute
  '/introducao': typeof IntroducaoRoute
  '/jornada': typeof JornadaRoute
  '/palavra-ao-leitor': typeof PalavraAoLeitorRoute
  '/por-que-40-dias': typeof PorQue40DiasRoute
  '/apresentacao/caminhada': typeof ApresentacaoCaminhadaRoute
  '/apresentacao/familia': typeof ApresentacaoFamiliaRoute
  '/dia/$numero': typeof DiaNumeroRoute
  '/apresentacao': typeof ApresentacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-viver': typeof ComoViverRoute
  '/entrar': typeof EntrarRoute
  '/forca-da-oracao': typeof ForcaDaOracaoRoute
  '/introducao': typeof IntroducaoRoute
  '/jornada': typeof JornadaRoute
  '/palavra-ao-leitor': typeof PalavraAoLeitorRoute
  '/por-que-40-dias': typeof PorQue40DiasRoute
  '/apresentacao/caminhada': typeof ApresentacaoCaminhadaRoute
  '/apresentacao/familia': typeof ApresentacaoFamiliaRoute
  '/dia/$numero': typeof DiaNumeroRoute
  '/apresentacao/': typeof ApresentacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-viver'
    | '/entrar'
    | '/forca-da-oracao'
    | '/introducao'
    | '/jornada'
    | '/palavra-ao-leitor'
    | '/por-que-40-dias'
    | '/apresentacao/caminhada'
    | '/apresentacao/familia'
    | '/dia/$numero'
    | '/apresentacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/como-viver'
    | '/entrar'
    | '/forca-da-oracao'
    | '/introducao'
    | '/jornada'
    | '/palavra-ao-leitor'
    | '/por-que-40-dias'
    | '/apresentacao/caminhada'
    | '/apresentacao/familia'
    | '/dia/$numero'
    | '/apresentacao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-viver'
    | '/entrar'
    | '/forca-da-oracao'
    | '/introducao'
    | '/jornada'
    | '/palavra-ao-leitor'
    | '/por-que-40-dias'
    | '/apresentacao/caminhada'
    | '/apresentacao/familia'
    | '/dia/$numero'
    | '/apresentacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComoViverRoute: typeof ComoViverRoute
  EntrarRoute: typeof EntrarRoute
  ForcaDaOracaoRoute: typeof ForcaDaOracaoRoute
  IntroducaoRoute: typeof IntroducaoRoute
  JornadaRoute: typeof JornadaRoute
  PalavraAoLeitorRoute: typeof PalavraAoLeitorRoute
  PorQue40DiasRoute: typeof PorQue40DiasRoute
  ApresentacaoCaminhadaRoute: typeof ApresentacaoCaminhadaRoute
  ApresentacaoFamiliaRoute: typeof ApresentacaoFamiliaRoute
  DiaNumeroRoute: typeof DiaNumeroRoute
  ApresentacaoIndexRoute: typeof ApresentacaoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-viver': {
      id: '/como-viver'
      path: '/como-viver'
      fullPath: '/como-viver'
      preLoaderRoute: typeof ComoViverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forca-da-oracao': {
      id: '/forca-da-oracao'
      path: '/forca-da-oracao'
      fullPath: '/forca-da-oracao'
      preLoaderRoute: typeof ForcaDaOracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introducao': {
      id: '/introducao'
      path: '/introducao'
      fullPath: '/introducao'
      preLoaderRoute: typeof IntroducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palavra-ao-leitor': {
      id: '/palavra-ao-leitor'
      path: '/palavra-ao-leitor'
      fullPath: '/palavra-ao-leitor'
      preLoaderRoute: typeof PalavraAoLeitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que-40-dias': {
      id: '/por-que-40-dias'
      path: '/por-que-40-dias'
      fullPath: '/por-que-40-dias'
      preLoaderRoute: typeof PorQue40DiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao/': {
      id: '/apresentacao/'
      path: '/apresentacao'
      fullPath: '/apresentacao/'
      preLoaderRoute: typeof ApresentacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao/caminhada': {
      id: '/apresentacao/caminhada'
      path: '/apresentacao/caminhada'
      fullPath: '/apresentacao/caminhada'
      preLoaderRoute: typeof ApresentacaoCaminhadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao/familia': {
      id: '/apresentacao/familia'
      path: '/apresentacao/familia'
      fullPath: '/apresentacao/familia'
      preLoaderRoute: typeof ApresentacaoFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia/$numero': {
      id: '/dia/$numero'
      path: '/dia/$numero'
      fullPath: '/dia/$numero'
      preLoaderRoute: typeof DiaNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComoViverRoute: ComoViverRoute,
  EntrarRoute: EntrarRoute,
  ForcaDaOracaoRoute: ForcaDaOracaoRoute,
  IntroducaoRoute: IntroducaoRoute,
  JornadaRoute: JornadaRoute,
  PalavraAoLeitorRoute: PalavraAoLeitorRoute,
  PorQue40DiasRoute: PorQue40DiasRoute,
  ApresentacaoCaminhadaRoute: ApresentacaoCaminhadaRoute,
  ApresentacaoFamiliaRoute: ApresentacaoFamiliaRoute,
  DiaNumeroRoute: DiaNumeroRoute,
  ApresentacaoIndexRoute: ApresentacaoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
